---
ansible_python_interpreter: '{{ ansible_playbook_python }}'

# Which operator to test.
operator_under_test: "{{ lookup('env', 'OPERATOR_UNDER_TEST') | default('helm') }}"

# The operator directory inside the testdata/[operator type] directory.
operator_subdir: memcached-operator

# See: https://github.com/operator-framework/operator-sdk-samples/issues/154
app_label_selector: app=memcached

# How many CRs to deploy.
memcached_cr_count: 3

# What version of operator-sdk to use for testing.
# NOTE: Keep in sync with operator RELEASE_VERSION in .github/workflows/CI.
operator_samples_version: v1.6.2

# Options for the Docker images and registry to use.
registry: ttl.sh
image_name: operator-sdk-performance-test
image_tag: 1h

# Options to specify ansible version and k8s collection version
# if ansible_version: '' or k8s_collection_version: '' the default version is used
ansible_version_to_be_used: ''
k8s_collection_version: '2.0.0'

# Versions for cluster addons.
#cert_manager_version: v0.16.1
cert_manager_version: v1.2.0
#prometheus_operator_version: v0.41.1
prometheus_operator_version: v0.48.1
metrics_server_version: v0.3.7
