---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - config.yml

  tasks:
    - name: Clone the operator-sdk project. (v1.8.0)
      git:
        repo: https://github.com/alinabuzachis/operator-sdk.git
        version: increase_helm_manager_memory_v1.8
        dest: ./operator-sdk
        force: yes
      when:
        - operator_samples_version == 'v1.8.0'
    
    - name: Clone the operator-sdk project. (v1.6.2)
      git:
        repo: https://github.com/alinabuzachis/operator-sdk.git
        version: increase_helm_manager_memory_v1.6
        dest: ./operator-sdk
        force: true
      when:
        - operator_samples_version == 'v1.6.2'
    
    - name: Attempt to fix file permissions.
      file:
        dest: ./operator-sdk
        mode: 0777
        recurse: true
    
    - name: Ensure the kubernetes.core collection is used (patch) - main.yml
      copy:
        src: ./templates/main.yml
        dest: ./operator-sdk/testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml
        follow: no
      when:
        - k8s_collection_version == '2.0.0'
    
    - name: Attempt to fix file permissions.
      file:
        dest: ./operator-sdk
        mode: 0777
        recurse: true

    - name: Deploy a memcached DaemonSet so image is pulled to all nodes.
      include_tasks: tasks/memcached-daemonset.yml

    - name: Deploy cert-manager (required for Go operator).
      include_tasks: tasks/cert-manager.yml
      when: "'go' == operator_under_test"

    - name: Deploy prometheus-operator (required for metrics service).
      include_tasks: tasks/prometheus-operator.yml

    - name: Build, deploy, benchmark, and undeploy operators.
      include_tasks: tasks/operator-tasks.yml
      loop: ["{{ operator_under_test }}"]
      register: molecule_result
      loop_control:
        loop_var: operator_type

