---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - config.yml

  tasks:
    - name: Clone the operator-sdk project.
      git:
        repo: https://github.com/alinabuzachis/operator-sdk.git
        version: increase_helm_manager_memory_v1.8
        #repo: https://github.com/operator-framework/operator-sdk.git
        #version: "{{ operator_samples_version }}" 
        dest: ./operator-sdk
        force: true

    - name: Attempt to fix file permissions.
      file:
        dest: ./operator-sdk
        mode: 0777
        recurse: true

    - name: Deploy a memcached DaemonSet so image is pulled to all nodes.
      include_tasks: tasks/memcached-daemonset.yml

    - name: Deploy cert-manager (required for Go operator).
      include_tasks: tasks/cert-manager.yml
      when: "'go' == operator_under_test"

    - name: Deploy prometheus-operator (required for metrics service).
      include_tasks: tasks/prometheus-operator.yml

    - name: Build, deploy, benchmark, and undeploy operators.
      include_tasks: tasks/operator-tasks.yml
      loop: ["{{ operator_under_test }}"]
      register: molecule_result
      loop_control:
        loop_var: operator_type

